#!/usr/bin/env python3

"""
Frost OS Root Filesystem Builder

Builds a Frost OS root filesystem from a minimal Arch Linux installation,
merges Arch's missing files into a temporary frost-root.ready/ copy,
creates a GPT/ext2 disk image from that ready tree, and can install the
resulting filesystem onto a real PARTITION.

Directory layout
----------------
    .
    ├── frost.py
    ├── frost-root/
    │   ├── bin/
    │   ├── etc/
    │   ├── usr/
    │   └── ...
    ├── frost-root.ready/       # generated working/final build tree
    ├── arch-root/              # temporary pacstrap filesystem
    └── disk.img

Build pipeline
--------------
    pacstrap
       |
       v
    arch-root/
       |
       |  clean Arch/pacman identity
       v
    frost-root/
       |
       |  copied FIRST to frost-root.ready/
       |  Arch fills only files missing from the ready tree
       v
    frost-root.ready/
       |
       v
    disk.img

IMPORTANT:
    frost-root/ is never modified by the Arch -> ready merge.

Merge rules
-----------
    frost-root/foo exists
        -> keep the Frost version

    frost-root/foo does not exist
        -> copy arch-root/foo into frost-root.ready/

    Both are directories
        -> recursively merge them

Therefore frost-root/ is the user's original source tree and
frost-root.ready/ is the generated final filesystem.

Commands
--------
    ./frost.py build-rootfs
    ./frost.py build-image
    ./frost.py build
    ./frost.py clean
    ./frost.py install /dev/sdX1

WARNING:
    The "install" command is DESTRUCTIVE. It formats ONLY the selected
    partition as ext2 and copies Frost onto it. Whole-disk devices are
    explicitly rejected, and the target must be an actual partition.
    No bootloader is installed.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


# ============================================================================
# Configuration
# ============================================================================

ROOT_DIR = Path(__file__).resolve().parent

# Temporary filesystem generated by pacstrap.
ARCH_ROOT = ROOT_DIR / "arch-root"

# Frost's ORIGINAL source filesystem.
#
# This directory is NEVER modified by the Arch -> ready merge.
FROST_ROOT = ROOT_DIR / "frost-root"

# Generated working/final filesystem.
#
# This is the only Frost tree modified during a build.
FROST_READY_ROOT = ROOT_DIR / "frost-root.ready"

# Generated disk image.
DISK_IMAGE = ROOT_DIR / "disk.img"

# Disk image size.
IMAGE_SIZE = "4G"

# Start of the first partition.
IMAGE_PARTITION_START = "1MiB"

# Packages installed by pacstrap.
PACSTRAP_PACKAGES = [
    "base",
]


# ============================================================================
# Color palette
# ============================================================================

BLUE = "\033[1;34m"
CYAN = "\033[1;36m"
WHITE = "\033[1;37m"
GRAY = "\033[0;90m"
BOLD = "\033[1m"
RESET = "\033[0m"
RED = "\033[1;31m"
YELLOW = "\033[1;33m"


# ============================================================================
# Output helpers
# ============================================================================

def info(*message: str) -> None:
    """Print an informational message."""
    print(f"{BLUE}[INFO]{RESET} {WHITE}{message}{RESET}")


def ok(*message: str) -> None:
    """Print a successful-operation message."""
    print(f"{CYAN}[ OK ]{RESET} {WHITE}{message}{RESET}")


def warn(*message: str) -> None:
    """Print a warning message."""
    print(f"{YELLOW}[WARN]{RESET} {message}")


def error(*message: str) -> None:
    """Print an error message."""
    print(f"{RED}[ERROR]{RESET} {message}", file=sys.stderr)


def section(*message: str) -> None:
    """Print a section heading."""
    print()
    print(f"{BLUE}{BOLD}== {message} =={RESET}")


# ============================================================================
# Command helpers
# ============================================================================

def command_exists(command: str) -> bool:
    """Check whether a command exists in PATH."""
    return shutil.which(command) is not None


def require_commands(commands: list[str]) -> None:
    """Verify that all required external commands exist."""
    missing = [
        command
        for command in commands
        if not command_exists(command)
    ]

    if not missing:
        return

    error("Missing required commands:")

    for command in missing:
        print(f"    {command}")

    sys.exit(1)


def run(
    command: list[str],
    *,
    check: bool = True,
    capture_output: bool = False,
) -> subprocess.CompletedProcess:
    """Execute an external command."""
    print(
        f"{GRAY}$ {' '.join(map(str, command))}{RESET}"
    )

    return subprocess.run(
        command,
        check=check,
        capture_output=capture_output,
        text=True,
    )


def sudo(
    command: list[str],
    **kwargs,
) -> subprocess.CompletedProcess:
    """Execute a command through sudo."""
    return run(
        ["sudo", *command],
        **kwargs,
    )


# ============================================================================
# Filesystem helpers
# ============================================================================

def remove_path(path: Path) -> None:
    """
    Remove a file, symlink, or directory.

    Uses sudo because generated root filesystems may contain files
    owned by root.
    """
    if not path.exists() and not path.is_symlink():
        return

    info(f"Removing {path}")

    sudo(
        [
            "rm",
            "-rf",
            "--",
            str(path),
        ]
    )


def copy_tree_as_root(
    source: Path,
    destination: Path,
) -> None:
    """
    Clone SOURCE into DESTINATION using cp -a.

    Ownership is deliberately not preserved because frost-root.ready
    needs to remain writable by the user while the Arch merge occurs.

    Symlinks, permissions, timestamps and other filesystem metadata are
    otherwise preserved by cp -a.
    """
    if not source.exists():
        raise RuntimeError(
            f"Source directory does not exist: {source}"
        )

    destination.mkdir(
        parents=True,
        exist_ok=True,
    )

    sudo(
        [
            "cp",
            "-a",
            "--no-preserve=ownership",
            f"{source}/.",
            f"{destination}/",
        ]
    )


def copy_missing_tree(source: Path, destination: Path) -> None:
    """
    Merge SOURCE into DESTINATION without overwriting anything that
    already exists in DESTINATION. Runs as root so unreadable files
    (shadow, gshadow, ...) can be copied.
    """
    if not source.exists():
        return

    destination.mkdir(parents=True, exist_ok=True)

    sudo([
        "rsync",
        "-a",                  # archive: perms, times, symlinks, etc.
        "--ignore-existing",   # never overwrite what Frost already has
        "--no-owner",
        "--no-group",
        f"{source}/",
        f"{destination}/",
    ])


# ============================================================================
# Arch root filesystem
# ============================================================================

def create_arch_rootfs() -> None:
    """
    Create a minimal Arch Linux root filesystem using pacstrap.

    The resulting filesystem is placed in:

        ./arch-root/
    """
    section("Creating Arch root filesystem")

    require_commands(
        [
            "sudo",
            "pacstrap",
        ]
    )

    # --------------------------------------------------------------
    # Remove previous arch-root.
    # --------------------------------------------------------------

    if ARCH_ROOT.exists():
        warn(
            f"{ARCH_ROOT} already exists."
        )

        answer = input(
            f"{BOLD}"
            "Delete the existing arch-root and recreate it? [y/N]: "
            f"{RESET}"
        ).strip().lower()

        if answer != "y":
            print("Aborted.")
            return

        remove_path(ARCH_ROOT)

    # --------------------------------------------------------------
    # Create directory.
    # --------------------------------------------------------------

    ARCH_ROOT.mkdir(
        parents=True,
        exist_ok=True,
    )

    # --------------------------------------------------------------
    # Run pacstrap.
    # --------------------------------------------------------------

    info(
        "Installing minimal Arch userspace with pacstrap..."
    )

    info(
        "Packages: "
        + " ".join(PACSTRAP_PACKAGES)
    )

    sudo(
        [
            "pacstrap",
            "-K",
            str(ARCH_ROOT),
            *PACSTRAP_PACKAGES,
        ]
    )

    ok(
        f"Arch root filesystem created at {ARCH_ROOT}"
    )


def clean_arch_identity() -> None:
    """
    Remove Arch, Manjaro, and pacman-specific files.

    The goal is to turn the pacstrap filesystem into a generic
    filesystem base for Frost.
    """
    section(
        "Removing Arch / Manjaro / pacman identity"
    )

    paths = [
        # Release / distribution identification.
        "/etc/arch-release",
        "/etc/lsb-release",
        "/etc/os-release",

        # pacman configuration.
        "/etc/pacman.conf",
        "/etc/pacman.d",

        # pacman databases and caches.
        "/var/lib/pacman",
        "/var/cache/pacman",

        # pacman executable/documentation.
        "/usr/bin/pacman",
        "/usr/share/pacman",
        "/usr/share/doc/pacman",
    ]

    for relative_path in paths:
        path = (
            ARCH_ROOT
            / relative_path.lstrip("/")
        )

        remove_path(path)

    ok(
        "Arch / Manjaro / pacman-specific files removed."
    )


# ============================================================================
# Frost root preparation / merge
# ============================================================================

def prepare_frost_ready() -> None:
    """
    Create a fresh frost-root.ready/ from the ORIGINAL frost-root/.

    frost-root/ is never used as the destination of the Arch merge.

    If frost-root.ready/ already exists, it is deleted first so no stale
    files from an older build can survive into the new build.
    """
    section("Preparing frost-root.ready")

    # --------------------------------------------------------------
    # Original Frost root must exist.
    # --------------------------------------------------------------

    if not FROST_ROOT.exists():
        error(
            f"{FROST_ROOT} does not exist."
        )

        error(
            "Create frost-root/ before running 'build-rootfs'."
        )

        sys.exit(1)

    if not FROST_ROOT.is_dir():
        error(
            f"{FROST_ROOT} is not a directory."
        )

        sys.exit(1)

    # --------------------------------------------------------------
    # Delete previous ready tree.
    # --------------------------------------------------------------

    if (
        FROST_READY_ROOT.exists()
        or FROST_READY_ROOT.is_symlink()
    ):
        info(
            f"Removing previous {FROST_READY_ROOT}"
        )

        remove_path(FROST_READY_ROOT)

    # --------------------------------------------------------------
    # Create fresh ready directory.
    # --------------------------------------------------------------

    FROST_READY_ROOT.mkdir(
        parents=True,
        exist_ok=True,
    )

    # --------------------------------------------------------------
    # Clone the ORIGINAL Frost tree.
    # --------------------------------------------------------------

    info(
        "Cloning original frost-root -> frost-root.ready..."
    )

    copy_tree_as_root(
        FROST_ROOT,
        FROST_READY_ROOT,
    )

    run([
        "sudo", "chown", "-R",
        f"{os.getuid()}:{os.getgid()}",
        str(FROST_READY_ROOT),
    ])

    ok(
        f"Original Frost tree cloned to {FROST_READY_ROOT}"
    )

    info(
        "The original frost-root/ has not been modified."
    )


def merge_arch_into_frost_ready() -> None:
    """
    Merge arch-root/ INTO frost-root.ready/.

    frost-root.ready/ already contains a complete copy of frost-root/,
    therefore every original Frost file has priority over Arch.

    The original frost-root/ is never modified.
    """
    section(
        "Merging Arch filesystem into frost-root.ready"
    )

    # --------------------------------------------------------------
    # Verify Arch root.
    # --------------------------------------------------------------

    if not ARCH_ROOT.exists():
        error(
            f"{ARCH_ROOT} does not exist."
        )

        error(
            "Run 'build-rootfs' again."
        )

        sys.exit(1)

    # --------------------------------------------------------------
    # Verify ready tree.
    # --------------------------------------------------------------

    if not FROST_READY_ROOT.exists():
        error(
            f"{FROST_READY_ROOT} does not exist."
        )

        error(
            "Prepare frost-root.ready before merging."
        )

        sys.exit(1)

    # --------------------------------------------------------------
    # Merge.
    # --------------------------------------------------------------

    info(
        "Frost source files have priority."
    )

    info(
        "Copying only files missing from frost-root.ready..."
    )

    copy_missing_tree(
        source=ARCH_ROOT,
        destination=FROST_READY_ROOT,
    )

    ok(
        f"Final generated filesystem: {FROST_READY_ROOT}"
    )


def build_rootfs() -> None:
    """
    Complete root filesystem build.

    Steps:

        1. pacstrap -> arch-root
        2. remove Arch/pacman identity from arch-root
        3. clone frost-root -> frost-root.ready
        4. merge arch-root -> frost-root.ready
        5. original frost-root remains untouched
    """
    section(
        "Frost root filesystem build"
    )

    create_arch_rootfs()

    clean_arch_identity()

    prepare_frost_ready()

    merge_arch_into_frost_ready()

    print()

    ok(
        f"Frost build tree ready: {FROST_READY_ROOT}"
    )

    ok(
        f"Original Frost source preserved: {FROST_ROOT}"
    )


# ============================================================================
# Disk image
# ============================================================================

def create_disk_image() -> None:
    """
    Create a 4 GiB GPT disk image.

    Layout:

        GPT
        └── Partition 1
            └── ext2
                └── frost-root.ready/

    The image is built ONLY from frost-root.ready/.
    """
    section(
        "Creating GPT disk image"
    )

    require_commands(
        [
            "sudo",
            "truncate",
            "parted",
            "losetup",
            "mkfs.ext2",
            "mount",
            "umount",
            "cp",
        ]
    )

    # --------------------------------------------------------------
    # Verify generated root filesystem.
    # --------------------------------------------------------------

    if not FROST_READY_ROOT.exists():
        error(
            f"{FROST_READY_ROOT} does not exist."
        )

        error(
            "Run 'build-rootfs' first."
        )

        sys.exit(1)

    # --------------------------------------------------------------
    # Remove old disk image.
    # --------------------------------------------------------------

    if DISK_IMAGE.exists():
        info(
            f"Removing old {DISK_IMAGE}"
        )

        DISK_IMAGE.unlink()

    # --------------------------------------------------------------
    # Create sparse image.
    # --------------------------------------------------------------

    info(
        f"Creating {IMAGE_SIZE} disk image..."
    )

    run(
        [
            "truncate",
            "-s",
            IMAGE_SIZE,
            str(DISK_IMAGE),
        ]
    )

    # --------------------------------------------------------------
    # GPT partition table.
    # --------------------------------------------------------------

    info(
        "Creating GPT partition table..."
    )

    run(
        [
            "parted",
            "-s",
            str(DISK_IMAGE),
            "mklabel",
            "gpt",
        ]
    )

    # --------------------------------------------------------------
    # Partition.
    # --------------------------------------------------------------

    info(
        "Creating primary ext2 partition..."
    )

    run(
        [
            "parted",
            "-s",
            str(DISK_IMAGE),
            "mkpart",
            "primary",
            "ext2",
            IMAGE_PARTITION_START,
            "100%",
        ]
    )

    loop_device: str | None = None

    mount_dir = Path(
        "/tmp/frost-root-image"
    )

    mounted = False

    try:
        # ----------------------------------------------------------
        # Attach loop device.
        # ----------------------------------------------------------

        section(
            "Attaching disk image"
        )

        result = sudo(
            [
                "losetup",
                "--find",
                "--show",
                "--partscan",
                str(DISK_IMAGE),
            ],
            capture_output=True,
        )

        loop_device = result.stdout.strip()

        if not loop_device:
            raise RuntimeError(
                "losetup did not return a loop device."
            )

        info(
            f"Loop device: {loop_device}"
        )

        partition = f"{loop_device}p1"

        # ----------------------------------------------------------
        # Format.
        # ----------------------------------------------------------

        info(
            "Formatting image partition as ext2..."
        )

        sudo(
            [
                "mkfs.ext2",
                "-F",
                partition,
            ]
        )

        # ----------------------------------------------------------
        # Mount.
        # ----------------------------------------------------------

        sudo(
            [
                "mkdir",
                "-p",
                str(mount_dir),
            ]
        )

        info(
            f"Mounting {partition}..."
        )

        sudo(
            [
                "mount",
                partition,
                str(mount_dir),
            ]
        )

        mounted = True

        try:
            # ------------------------------------------------------
            # Copy generated final Frost filesystem.
            # ------------------------------------------------------

            section(
                "Copying generated Frost filesystem"
            )

            info(
                "Copying frost-root.ready into the disk image..."
            )

            sudo(
                [
                    "cp",
                    "-a",
                    f"{FROST_READY_ROOT}/.",
                    f"{mount_dir}/",
                ]
            )

            # ------------------------------------------------------
            # Flush buffers.
            # ------------------------------------------------------

            info(
                "Synchronizing filesystem..."
            )

            sudo(
                [
                    "sync"
                ]
            )

        finally:
            # ------------------------------------------------------
            # Unmount.
            # ------------------------------------------------------

            if mounted:
                info(
                    "Unmounting image filesystem..."
                )

                sudo(
                    [
                        "umount",
                        str(mount_dir),
                    ],
                    check=False,
                )

                mounted = False

    finally:
        # ----------------------------------------------------------
        # Detach loop device.
        # ----------------------------------------------------------

        if loop_device:
            info(
                f"Detaching {loop_device}..."
            )

            sudo(
                [
                    "losetup",
                    "-d",
                    loop_device,
                ],
                check=False,
            )

        # ----------------------------------------------------------
        # Remove temporary mount directory.
        # ----------------------------------------------------------

        try:
            if mount_dir.exists():
                mount_dir.rmdir()
        except OSError:
            pass

    ok(
        f"disk.img ready: {DISK_IMAGE}"
    )


# ============================================================================
# Clean
# ============================================================================

def clean() -> None:
    """
    Remove generated build artifacts:

        disk.img
        frost-root.ready/
        arch-root/

    The ORIGINAL frost-root/ is deliberately NOT removed.
    """
    section(
        "Cleaning Frost build artifacts"
    )

    targets = [
        DISK_IMAGE,
        FROST_READY_ROOT,
        ARCH_ROOT,
    ]

    removed_any = False

    for target in targets:
        if (
            target.exists()
            or target.is_symlink()
        ):
            remove_path(target)
            removed_any = True
        else:
            info(
                f"Not present: {target}"
            )

    if removed_any:
        ok(
            "Generated build artifacts removed."
        )
    else:
        ok(
            "Nothing to clean."
        )

    info(
        f"Preserved: {FROST_ROOT}"
    )


# ============================================================================
# Real partition installer
# ============================================================================

def get_block_device_info(
    device: str,
) -> str:
    """
    Return human-readable information about a block device.
    """
    result = sudo(
        [
            "lsblk",
            "-o",
            "NAME,SIZE,TYPE,FSTYPE,LABEL,MOUNTPOINTS,MODEL",
            device,
        ],
        capture_output=True,
        check=False,
    )

    return result.stdout.strip()


def device_exists(
    device: Path,
) -> bool:
    """
    Check whether the specified path exists and is a block device.
    """
    if not device.is_absolute():
        return False

    try:
        return (
            os.path.exists(device)
            and os.path.exists(
                f"/sys/class/block/{device.name}"
            )
        )
    except OSError:
        return False


def get_block_device_type(
    device: str,
) -> str | None:
    """
    Return the lsblk TYPE for the exact supplied device.

    Expected result for installation is:

        part
    """
    result = subprocess.run(
        [
            "lsblk",
            "-dn",
            "-o",
            "TYPE",
            device,
        ],
        capture_output=True,
        text=True,
        check=False,
    )

    device_type = result.stdout.strip()

    if not device_type:
        return None

    return device_type


def is_partition(
    device: str,
) -> bool:
    """
    Return True only when the exact target device is an lsblk partition.

    lsblk reports partitions as TYPE=part.
    """
    return get_block_device_type(device) == "part"


def is_whole_disk(
    device: str,
) -> bool:
    """
    Return True when the exact target is an lsblk whole disk.
    """
    return get_block_device_type(device) == "disk"


def get_mountpoints(
    device: str,
) -> list[str]:
    """
    Return mountpoints associated with a device.
    """
    result = sudo(
        [
            "lsblk",
            "-n",
            "-o",
            "MOUNTPOINTS",
            device,
        ],
        capture_output=True,
        check=False,
    )

    return [
        line.strip()
        for line in result.stdout.splitlines()
        if line.strip()
    ]


def install_rootfs(
    device: str,
) -> None:
    """
    Install Frost onto a REAL PARTITION.

    THIS IS DESTRUCTIVE.

    The target must be an actual lsblk partition (TYPE=part).
    Whole disks (TYPE=disk), loop devices, etc. are rejected.

    The target partition is formatted as ext2 and frost-root.ready/
    is copied onto it.
    """
    section(
        "FROST INSTALLER"
    )

    require_commands(
        [
            "sudo",
            "lsblk",
            "mkfs.ext2",
            "mount",
            "umount",
            "cp",
        ]
    )

    # ----------------------------------------------------------------
    # Verify generated Frost filesystem.
    # ----------------------------------------------------------------

    if not FROST_READY_ROOT.exists():
        error(
            f"{FROST_READY_ROOT} does not exist."
        )

        error(
            "Run 'build-rootfs' first."
        )

        sys.exit(1)

    target = Path(device)

    # ----------------------------------------------------------------
    # Absolute path required.
    # ----------------------------------------------------------------

    if not target.is_absolute():
        error(
            "Target must be an absolute device path."
        )

        error(
            "Example: /dev/sda2"
        )

        error(
            "Example: /dev/nvme0n1p3"
        )

        sys.exit(1)

    # ----------------------------------------------------------------
    # Device must exist and be a block device.
    # ----------------------------------------------------------------

    if not device_exists(target):
        error(
            f"{target} does not appear to be a valid block device."
        )

        sys.exit(1)

    # ----------------------------------------------------------------
    # Identify exact target TYPE before anything destructive.
    # ----------------------------------------------------------------

    device_type = get_block_device_type(
        str(target)
    )

    if device_type is None:
        error(
            f"Could not determine the device type of {target}."
        )

        error(
            "Refusing to continue."
        )

        sys.exit(1)

    print()

    print(
        f"{BOLD}Target device type:{RESET} "
        f"{device_type}"
    )

    # ----------------------------------------------------------------
    # HARD partition-only safety check.
    #
    # Only TYPE=part is accepted.
    # ----------------------------------------------------------------

    if not is_partition(str(target)):
        print()

        if is_whole_disk(str(target)):
            error(
                "REFUSING TO INSTALL ON A WHOLE DISK."
            )
        else:
            error(
                f"REFUSING TO INSTALL ON {target}: "
                f"device type is '{device_type}', "
                "not 'part'."
            )

        error(
            "The install command accepts PARTITIONS ONLY."
        )

        error(
            "Examples of accepted targets:"
        )

        error(
            "    /dev/sda2"
        )

        error(
            "    /dev/nvme0n1p3"
        )

        error(
            "    /dev/mmcblk0p1"
        )

        error(
            "The complete disk must never be supplied."
        )

        sys.exit(1)

    # ----------------------------------------------------------------
    # MASSIVE WARNING.
    # ----------------------------------------------------------------

    print()

    print(
        f"{RED}{BOLD}"
        "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
        f"{RESET}"
    )

    print(
        f"{RED}{BOLD}"
        "!!             DESTRUCTIVE OPERATION         !!"
        f"{RESET}"
    )

    print(
        f"{RED}{BOLD}"
        "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
        f"{RESET}"
    )

    print()

    warn(
        "THE SELECTED PARTITION WILL BE FORMATTED."
    )

    warn(
        "ALL DATA CURRENTLY STORED ON IT WILL BE ERASED."
    )

    warn(
        "THIS OPERATION CANNOT BE UNDONE."
    )

    print()

    print(
        f"{BOLD}Target:{RESET} {target}"
    )

    print()

    # ----------------------------------------------------------------
    # Show device information.
    # ----------------------------------------------------------------

    print(
        get_block_device_info(
            str(target)
        )
    )

    print()

    # ----------------------------------------------------------------
    # Refuse mounted targets.
    # ----------------------------------------------------------------

    mountpoints = get_mountpoints(
        str(target)
    )

    if mountpoints:
        error(
            "TARGET PARTITION IS CURRENTLY MOUNTED:"
        )

        for mountpoint in mountpoints:
            error(
                f"    {mountpoint}"
            )

        print()

        error(
            "Unmount the partition before continuing."
        )

        sys.exit(1)

    # ----------------------------------------------------------------
    # First confirmation.
    # ----------------------------------------------------------------

    print()

    print(
        f"{BOLD}"
        "To continue, type the EXACT device path:"
        f"{RESET}"
    )

    typed_device = input(
        ">>> "
    ).strip()

    if typed_device != str(target):
        error(
            "Device path did not match."
        )

        error(
            "Installation cancelled."
        )

        sys.exit(1)

    # ----------------------------------------------------------------
    # Second confirmation.
    # ----------------------------------------------------------------

    print()

    print(
        f"{RED}{BOLD}"
        "FINAL WARNING"
        f"{RESET}"
    )

    print()

    print(
        f"This will ERASE {target}."
    )

    print(
        "The partition will be formatted as ext2."
    )

    print(
        "Frost OS will then be copied onto it."
    )

    print()

    confirmation = input(
        f"{RED}{BOLD}"
        f"Type 'ERASE {target.name}' to continue: "
        f"{RESET}"
    ).strip()

    if confirmation != f"ERASE {target.name}":
        error(
            "Final confirmation failed."
        )

        error(
            "Installation cancelled."
        )

        sys.exit(1)

    # ----------------------------------------------------------------
    # Re-check exact target immediately before formatting.
    # ----------------------------------------------------------------

    final_type = get_block_device_type(
        str(target)
    )

    if final_type != "part":
        error(
            "Target changed state: "
            f"expected partition, got {final_type!r}."
        )

        error(
            "Refusing to format it."
        )

        sys.exit(1)

    # ----------------------------------------------------------------
    # Format.
    # ----------------------------------------------------------------

    section(
        "Formatting target"
    )

    info(
        f"Formatting partition {target} as ext2..."
    )

    sudo(
        [
            "mkfs.ext2",
            "-F",
            str(target),
        ]
    )

    # ----------------------------------------------------------------
    # Temporary mount directory.
    # ----------------------------------------------------------------

    mount_dir = Path(
        tempfile.mkdtemp(
            prefix="frost-install-",
            dir="/tmp",
        )
    )

    mounted = False

    try:
        # ------------------------------------------------------------
        # Mount.
        # ------------------------------------------------------------

        info(
            f"Mounting {target}..."
        )

        sudo(
            [
                "mount",
                str(target),
                str(mount_dir),
            ]
        )

        mounted = True

        # ------------------------------------------------------------
        # Copy generated final Frost filesystem.
        # ------------------------------------------------------------

        section(
            "Installing Frost filesystem"
        )

        info(
            "Copying frost-root.ready..."
        )

        sudo(
            [
                "cp",
                "-a",
                f"{FROST_READY_ROOT}/.",
                f"{mount_dir}/",
            ]
        )

        # ------------------------------------------------------------
        # Synchronize.
        # ------------------------------------------------------------

        info(
            "Synchronizing filesystem..."
        )

        sudo(
            [
                "sync"
            ]
        )

        ok(
            "Frost filesystem copied successfully."
        )

    finally:
        # ------------------------------------------------------------
        # Unmount.
        # ------------------------------------------------------------

        if mounted:
            info(
                "Unmounting target..."
            )

            sudo(
                [
                    "umount",
                    str(mount_dir),
                ],
                check=False,
            )

        # ------------------------------------------------------------
        # Remove temporary mount directory.
        # ------------------------------------------------------------

        try:
            mount_dir.rmdir()
        except OSError:
            pass

    # ----------------------------------------------------------------
    # Finished.
    # ----------------------------------------------------------------

    section(
        "Installation complete"
    )

    ok(
        f"Frost OS installed to partition {target}"
    )

    warn(
        "The partition contains an ext2 filesystem."
    )

    warn(
        "No bootloader was installed."
    )


# ============================================================================
# Argument parser
# ============================================================================

def build_parser() -> argparse.ArgumentParser:
    """
    Construct the command-line interface.
    """
    parser = argparse.ArgumentParser(
        description=(
            "Frost OS root filesystem and disk image builder."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:

    Build root filesystem:
        %(prog)s build-rootfs

    Build disk image from frost-root.ready:
        %(prog)s build-image

    Build everything:
        %(prog)s build

    Clean generated artifacts:
        %(prog)s clean

    Install onto a PARTITION:
        %(prog)s install /dev/sda2
        %(prog)s install /dev/nvme0n1p3

The install command rejects whole disks and accepts only lsblk TYPE=part.
""",
    )

    subparsers = parser.add_subparsers(
        dest="command",
        required=True,
    )

    # ----------------------------------------------------------------
    # build-rootfs
    # ----------------------------------------------------------------

    subparsers.add_parser(
        "build-rootfs",
        help=(
            "Create arch-root, clone frost-root to frost-root.ready, "
            "and merge Arch into the ready tree"
        ),
    )

    # ----------------------------------------------------------------
    # build-image
    # ----------------------------------------------------------------

    subparsers.add_parser(
        "build-image",
        help=(
            "Create disk.img from frost-root.ready"
        ),
    )

    # ----------------------------------------------------------------
    # build
    # ----------------------------------------------------------------

    subparsers.add_parser(
        "build",
        help=(
            "Build frost-root.ready and disk.img"
        ),
    )

    # ----------------------------------------------------------------
    # clean
    # ----------------------------------------------------------------

    subparsers.add_parser(
        "clean",
        help=(
            "Remove disk.img, frost-root.ready, and arch-root "
            "(never frost-root)"
        ),
    )

    # ----------------------------------------------------------------
    # install
    # ----------------------------------------------------------------

    install_parser = subparsers.add_parser(
        "install",
        help=(
            "DESTRUCTIVELY install Frost onto a PARTITION"
        ),
    )

    install_parser.add_argument(
        "device",
        help=(
            "Target partition, e.g. /dev/sda2"
        ),
    )

    return parser


# ============================================================================
# Main
# ============================================================================

def main() -> int:
    """
    Program entry point.
    """
    parser = build_parser()
    args = parser.parse_args()

    try:
        # ------------------------------------------------------------
        # Build root filesystem.
        # ------------------------------------------------------------

        if args.command == "build-rootfs":
            build_rootfs()

        # ------------------------------------------------------------
        # Build disk image.
        # ------------------------------------------------------------

        elif args.command == "build-image":
            create_disk_image()

        # ------------------------------------------------------------
        # Build everything.
        # ------------------------------------------------------------

        elif args.command == "build":
            build_rootfs()
            create_disk_image()

        # ------------------------------------------------------------
        # Clean.
        # ------------------------------------------------------------

        elif args.command == "clean":
            clean()

        # ------------------------------------------------------------
        # Install onto real partition.
        # ------------------------------------------------------------

        elif args.command == "install":
            install_rootfs(
                args.device
            )

        else:
            parser.print_help()
            return 1

    except KeyboardInterrupt:
        print()

        warn(
            "Operation interrupted by user."
        )

        return 130

    except subprocess.CalledProcessError as exc:
        print()

        error(
            f"Command failed with exit status "
            f"{exc.returncode}."
        )

        return exc.returncode

    except Exception as exc:
        print()

        error(
            str(exc)
        )

        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(
        main()
    )